### ISSUE TITLE
Create a new release via REST framework

### ISSUE THREAD

**Issue by stevinus1** [sw360/sw360rest#5]
Is it possible to create a release for a component via the REST framework? 

POST method doesn't seem to create a new release, which makes sense, as it seems illogical for a release to be created without a corresponding component. However, since it also seems to be impossible to link a release that doesn't already exist to a component via POST method, this functionality then doesn't seem to exist. 

Thanks for any help

**Comment by toedter** [comment]
you can create releases for components. Please take a look at the code of the sub-project demo-app, see https://github.com/sw360/sw360rest/blob/master/subprojects/demo-app/src/main/java/org/eclipse/sw360/rest/demo/JavaApi.java (see method createRelease)

The important part is, that you pass the URI of the component, not the id. That is the way Spring Data REST handles linking of REST resources.

A running demo (which actually run the demo app to initialize the data) you can find here: http://35.157.20.116:8091/browser.html#/api

**Comment by stevinus1** [comment]
Thank you, that was really helpful.
